name: padidja_expense_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  fl_chart: ^1.0.0
  share_plus: 11.0.0
  uuid: ^4.4.0
  connectivity_plus: ^4.0.2
  pdf: ^3.11.3
  printing: ^5.14.2
  intl: ^0.18.1
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  file_picker: ^10.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

# ✅ Ce bloc DOIT être hors de `flutter:`
flutter_native_splash:
  color: "#6074F9"
  image: assets/logo.png
  branding: assets/logo.png
  android: true
  ios: true
